Add support for Switch
d-edge/Cardidy pull request #97
Opened 2022-10-01 12:25 UTC by ntbm

Closes #21

2022-10-02 00:09 UTC, aloisdg commented
The tests are failing. Could you fix them?

```
A total of 1 test files matched the specified pattern.
  Failed ShouldIdentifyAsMaestros("6759710000901011") [66 ms]
  Error Message:
     Expected is <DEdge.CardType[3]>, actual is <System.Linq.Enumerable+WhereSelectArrayIterator`2[DEdge.Model.ICard,DEdge.CardType]>
  Values differ at index [2]
  Expected: GPN
  But was:  Switch
```

source: https://github.com/d-edge/Cardidy/actions/runs/3164565462/jobs/5156547997#step:6:1

2022-10-02 07:49 UTC, ntbm commented
Repushed a signed version of the code.
Also fixed the tests.
Sorry for not running them before and also thank you for providing me an opportunity to learn about payment cards :)

2022-10-02 09:47 UTC, aloisdg commented
You are welcome. Thanks for you work!

2022-10-07 14:16 UTC, aloisdg requested changes

2022-10-07 14:16 UTC, aloisdg commented on src/DEdge.Cardidy/Model/Cards.cs
> +    public Switch() : base(CardType.Switch, new []{4903, 4905, 4911, 4936, 564182, 633110, 6333, 6759}, From16To19) { }
@ntbm up ;)

2022-10-27 15:50 UTC, torendil approved these changes
Hey! LGTM :)

2022-10-27 15:53 UTC, aloisdg approved these changes

2022-10-27 15:53 UTC, merged